# Enter application name as seen on http://appengine.google.com
application: appnamehere
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /images
  static_dir: content/images

- url: /other
  static_dir: content/other

- url: /.*
  script: app.routes.app

libraries:
- name: jinja2
  version: latest
